# Deployment - Pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-cicd
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: mynginx-container
        image: gcr.io/google-samples/hello-app:1.0
      - name: my-sidecar
        image: busybox
        command: ["sh","-c","while true; do echo Doing sidecar stuff!; sleep 60; done"]
      tolerations:
      - key: env
        operator: Equal
        value: prod
        effect: NoSchedule